search_space:
   hidden_dim: 
    _type: choice
    _value: [128,256,512]
   lr: 
    _type: choice
    _value: [0.001,0.0001,0.0003]
   d_model: 
    _type: choice
    _value: [128,256,512]
   d_layers: 
    _type: choice
    _value: [1,2,3]
   e_layers: 
    _type: choice
    _value: [1,2,3]

trial_command: python main_nni.py --stage train --model_id itransformer_more_scale --model_name itransformer --log_path log --trainset_csv_path /data1/peizhongyi/applications/Goldwind_2020_Guangxi_CMA_001_trainset_target.csv --validset_csv_path /data1/peizhongyi/applications/Goldwind_2020_Guangxi_CMA_001_validset_target.csv --testset_csv_path /data1/peizhongyi/applications/Goldwind_2020_Guangxi_CMA_001_testset_target.csv --datetime_col dtime --feature_cols stn_id,latitude,longitude,ghi_sfc,rain_sfc,snow_sfc,tskin_sfc,tdew2m_sfc,clflo_sfc,clfmi_sfc,clfhi_sfc,wspd_10,wdir_10,t_10,p_10,rhoair_10,rh_10,wspd_30,wdir_30,t_30,p_30,rhoair_30,rh_30,wspd_50,wdir_50,t_50,p_50,rhoair_50,rh_50,wspd_70,wdir_70,t_70,p_70,rhoair_70,rh_70,wspd --target_cols wspd --seq_len 48 --label_len 12 --pred_len 48 --interval 900 --timestamp_feature h --train_epochs 50 --gpu 0

trial_code_directory: .

trial_gpu_number: 1
trial_concurrency: 8
max_trial_number: 400
max_experiment_duration: 2h

tuner:
  name: TPE
  class_args:
    optimize_mode: minimize

training_service:
  platform: local
  use_activeGpu: True

